name: Cleanup packages

on:
  schedule:
  - cron: '21 0 * * 6'
  workflow_dispatch:

jobs:
  clean-pr-packages:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/delete-package-versions@v5
      with:
        package-name: CenterEdge.Async
        package-type: nuget
        min-versions-to-keep: 30
        ignore-versions: ^(?!.*PullRequest).*$
